apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany, ReadOnlyMany depending on your needs
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabytes of storage
